# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.3"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 6.4"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = ">= 6.4"
    }
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
  }
}
